CREATE EXTENSION IF NOT EXISTS postgis;

CREATE ROLE bharosa_app WITH LOGIN PASSWORD 'bharosa_app' NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS;

GRANT CONNECT ON DATABASE bharosa TO bharosa_app;
GRANT USAGE, CREATE ON SCHEMA public TO bharosa_app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO bharosa_app;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO bharosa_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO bharosa_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO bharosa_app;
