from app.domains.identity.authorization import (
    ActorContext,
    Capability,
    SigningNotAuthorizedError,
)
from app.domains.identity.canonical import SignedPayloadFields, build_canonical_payload
from app.domains.identity.factory import NoProductionSignerConfiguredError, get_signer
from app.domains.identity.lifecycle import (
    IllegalLifecycleTransitionError,
    is_terminal,
    legal_next_states,
)
from app.domains.identity.models import (
    TRUSTED_KEY_STATUSES,
    Batch,
    BatchStatus,
    IdentityEventType,
    IdentityIssuanceEvent,
    KeyStatus,
    LifecycleState,
    Manufacturer,
    ManufacturerKey,
    ManufacturerStatus,
    Product,
    ProductIdentity,
    ProductStatus,
)
from app.domains.identity.service import (
    AuthenticityResult,
    CrossManufacturerKeyMismatchError,
    IssuedKey,
    issue_manufacturer_key,
    mark_manufacturer_key_compromised,
    open_batch,
    register_manufacturer,
    register_product,
    reserve_identity,
    revoke_manufacturer_key,
    sign_identity,
    transition_identity,
    verify_cryptographic_authenticity,
)
from app.domains.identity.signer import DevelopmentOnlySigner, GeneratedKey, Signer

__all__ = [
    "Manufacturer",
    "ManufacturerStatus",
    "ManufacturerKey",
    "KeyStatus",
    "TRUSTED_KEY_STATUSES",
    "Product",
    "ProductStatus",
    "Batch",
    "BatchStatus",
    "ProductIdentity",
    "LifecycleState",
    "IdentityIssuanceEvent",
    "IdentityEventType",
    "SignedPayloadFields",
    "build_canonical_payload",
    "Signer",
    "DevelopmentOnlySigner",
    "GeneratedKey",
    "get_signer",
    "NoProductionSignerConfiguredError",
    "IllegalLifecycleTransitionError",
    "legal_next_states",
    "is_terminal",
    "Capability",
    "ActorContext",
    "SigningNotAuthorizedError",
    "register_manufacturer",
    "issue_manufacturer_key",
    "IssuedKey",
    "register_product",
    "open_batch",
    "reserve_identity",
    "sign_identity",
    "transition_identity",
    "verify_cryptographic_authenticity",
    "AuthenticityResult",
    "CrossManufacturerKeyMismatchError",
    "revoke_manufacturer_key",
    "mark_manufacturer_key_compromised",
]
